### ISSUE TITLE
Create PEG.js style HTML tag parser and validator

### ISSUE THREAD

**Issue by nwronski** [codeschool/htmlTagValidator#5]
## Milestones for html-tag-validator

- [x] **[0.1.x]** Done
  - [x] Validate HTML documents against HTML 5 spec
  - [x] Parsing an HTML document to generate an AST
  - [x] `doctype` definition
  - [x] HTML 5 elements
  - [x] HTML 5 attributes
  - [x] Enhanced validation for `script`, `style`, `link` and `meta` elements
  - [x] Basic support for `iframe` elements
  - [x] HTML comments
  - [x] Conditional comments
  - [x] Allowed `<input>` element `type` values and the attributes supported by each `type`
  - [x] A properly-formed HTML 5 document should have a `<title>` element with contents
  - [x] Void elements
  - [x] Void and normal attributes
  - [x] and more!
- [x] **[0.2.x]** Current
  - [x] Allow for `options` to be provided to parser before running
  - [x] Create documentation for 0.2.x release
  - [x] Correct attribute validation for `input` tags based on `type`
- [ ] **[0.3.x]** Planned
  - [ ] **[In Progress]** Have strict and non-strict attribute and tag modes
  - [ ] Ability to preserve whitespace in `pre` tags
  - [ ] Allow plugins to extend validations performed by parser
- [ ] **[0.4.x]** Planned
  - [ ] Have a tool for traversing the AST generated by the parser

- [x] Set up grunt and create tasks to automate development, testing, building, etc...

### HTML attributes

- [x] Regular `value="bees"` and `value='bees'`
- [x] Attributes without quotes `value=1`
- [x] Attributes without values `checked`
- [x] Angular 2.0 values `[checked]="true"` `(click)="myFunc()"`
- [x] Inline `style` declarations `style="color: bold; content: 'my text';"`
- [x] Inline JavaScript in event attributes `click="run(event)"`

### Self-closing tags

- [x] Enforce whitelist of self-closing tags
- ~~Enforce rule against invalid XHTML format `<img src="cat.gif" />`~~ this is okay/ignored according to spec
- [x] Support self-closing tag syntax

  ``` html
  <img src="cat.gif">
  ```

### HTML `DOCTYPE` declarations

- [x] Support `DOCTYPE` syntax
- [x] Enforce correct `DOCTYPE` position in document
- [x] Allow for having a `DOCTYPE` definition inside of an `iframe` element within a parent document

  ``` html
  <!DOCTYPE html>
  ```

### Special tags

- [x] whitelist of allowed attributes `global` and `event` for all special tags
- [x] whitelist of `required`, `normal`, and `void` attributes for each special tag

#### Hierarchal rules

- [x] If you omit the `title` tag, the document will not validate as HTML
- [x] You can not have more than one `title` element in an HTML document
- [x] The `link` element goes only in the `head` section of an HTML document
- [x] The `meta` element goes only in the `head` section of an HTML document
- [x] If the "scoped" attribute is not used, each `style` tag must be located in the `head` section.

#### Tag-specific rules

- [x] `title`
  - [x] `title` tag is required to have content between the start and end tags

    ``` html
    <head>
      <title>Nick's happy fun page</title>
    </head>
    ```

- [x] `script` tags
  - [x] validate `script` tags only have specific attributes
  - [x] a `script` tag cannot have a `src` AND contents at the same time

  ```html
  <script type="text/javascript" async src="cat.js"></script>
  ```

- [x] `style` tags
  - [x] validate `style` tags only have specific attributes

  ```html
  <style type="text/css"></style>
  ```

- [x] `iframe` tags
  - [x] validate `iframe` tags only have specific attributes

  ```html
  <iframe src="cats.html"></iframe>
  ```

- [ ] `pre` tags
  - [ ] parse `pre` tags without trimming like regular elements
    - **moved to milestones for 0.3.x release**
    - This is tricky because there could still be other HTML elements within the `pre` tag that should still be parsed

    ``` html
    <pre>

      The whitespace above, below and          here
      should be preserved.

    </pre>
    ```

- [x] `link` tags
  - [x] validate `link` tags as void elements with specific attributes

    ``` html
    <head>
      <link rel="stylesheet" type="text/css" href="theme.css">
    </head>
    ```

- [x] `meta` tags
  - [x] validate `meta` tags as void elements
  - [x] validate `meta` tags only have specific attributes
  - [x] validate `meta` tags have specific rules for `content`, `name` and `http-equiv` attributes

    ``` html
    <head>
      <meta charset="UTF-8">
      <meta name="author" content="Nick Wronski">
    </head>
    ```

- [x] `input` tags
  - [x] Correct attribute validation for `input` tags based on `type`

    ``` html
    <input type="checkbox" checked="checked">
    ```

### Text nodes
- [x] parse text nodes

  ``` html
  <p>
    text node
    <strong>content within strong tag</strong>
  </p>
  ```

### Comment nodes
- [x] parse block comments

  ``` html
  <!--This is a comment. Comments are not displayed in the browser-->
  ```

### Conditional comments
- [x] parse conditional comments

  ``` html
  <!--[if gte mso 12]>
    <style>
      td {
        mso-line-height-rule: exactly;
      }
    </style>
  <![endif]-->
  ```

### Create standard AST format

- Base format and `DOCTYPE`
  - [x] `DOCTYPE`
  - [x] base format
    - object for single root element, or array for multiple root elements

  ```
  doctype:    html
  document:   []
  ```

- `element` (includes `link` and `meta` special tags)
  - [x] self-closing

    ```
    type:       element
    void:       true
    name:       input
    attributes:
      value:    bees
    children:   []
    ```

  - [x] normal (closing)

    ```
    type:       element
    void:       false
    name:       div
    attributes: {}
    children:   []
    ```

- [x] `script`, `style`

  ```
  type:       script
  attributes:
    type:     text/javascript
  contents:
    """

      var Cat;

      Cat = (function() {
        function Cat(name1) {
          this.name = name1;
        }

        Cat.prototype.meow = function() {
          return "Meow, my name is " + name + "!";
        };

        return Cat;

      })();

      var myCat = new Cat("Catherine Catterson");
      alert(myCat.meow());

    """
  ```

- [x] `style`

  ```
  type:       style
  attributes:
    type: text/css
  contents:
    """

      p {
        color: black;
      }

      body {
        background-color: white;
      }

      .main {
        color: #FF1212;
        font-weight: bold;
      }

    """
  ```

- [x] `title`

  ```
  type:       title
  attributes: {}
  contents:   Nick's happy fun page
  ```

- [x] `iframe`

  ```
  type:         iframe
  attributes:
    height:     300px
    width:      400px
  contents:
    doctype:    html
    document:   []
  ```

- [x] `text`

  ```
  type:     text
  contents: Hello there
  ```

- `comment`
  - [x] block comment

    ```
    type:        comment
    conditional: false
    condition:   null
    children:
      type:     text
      contents: Some sort of html comment
    ```

  - [x] conditional block comment

    ```
    type:        comment
    conditional: true
    condition:   if ie 8
    children:
      type:       element
      void:       false
      name:       p
      attributes: {}
      children:
        -
          type:     text
          contents: IE is version 8!
    ```

- [x] Have parser export AST
  - Partially completed (does not have all types yet)

### AST spec (in progress)

``` json
{
  "doctype": "html",
  "document": {
    "type": "element",
    "void": false,
    "name": "html",
    "attributes": { },
    "children": [
      {
        "type": "element",
        "void": false,
        "name": "head",
        "attributes": {},
        "children": [
          {
            "type": "script",
            "contents": "function myFunc() { console.log('hello, world!'); };"
          },
          {
            "type": "script",
            "attributes": {
              "type": "javascript",
              "src": "path/to/my/script.js"
            },
            "contents": null
          }
        ]
      },
      {
        "type": "element",
        "void": false,
        "name": "body",
        "attributes": {
          "class": "class1 class2",
          "bgcolor": "black"
        },
        "children": [
          {
            "type": "text",
            "content": "I am some text"
          },
          {
            "type": "element",
            "void": false,
            "name": "p",
            "attributes": {
              "id": "myPTag",
              "style": "font-weight: bold;"
            },
            "children": [
              {
               "type": "text",
               "content": "I am some more text"
              }
            ]
          }
        ]
      }
    ]
  }
}
```

**Comment by nwronski** [comment]
ready to publish
